apiVersion: v1
kind: Secret
metadata:
  name: fit-log-secret
  namespace: fit-log
type: Opaque
stringData:
  DATABASE_URL: "${DATABASE_URL}"
  GEMINI_API_KEY: "${GEMINI_API_KEY}"
  JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
