apiVersion: v1
kind: Secret
metadata:
  name: fit-log-secret
  namespace: fit-log
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://postgres:postgres@postgres-service:5432/fitlog_db"
  GEMINI_API_KEY: "${GEMINI_API_KEY}"
  JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
