apiVersion: v1
kind: Service
metadata:
  name: fit-log-service
  namespace: fit-log
  labels:
    app: fit-log
spec:
  type: NodePort
  selector:
    app: fit-log
  ports:
    - port: 80
      targetPort: 9281
      nodePort: 30006
